#!/usr/bin/env node
// Emits the Supabase migration that seeds the Agentic Marketing Team framework
// into ai-blueprint-builder.
//
// This is the whole "git → app" sync, and it's deliberately not a service: git
// owns the node model, this script turns it into SQL, and you review the result
// as a diff like any other migration.
//
// Every insert is ON CONFLICT DO NOTHING. Re-running seeds what's missing and
// never overwrites a question someone has since edited in /admin/framework.
//
//   node scripts/seed-sql.mjs > ../ai-blueprint-builder/supabase/migrations/015_seed_agentic_team.sql

import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const { nodes, interviews } = JSON.parse(readFileSync(join(ROOT, "site", "nodes.json"), "utf8"));

/** Deterministic UUIDv5-shaped id, so re-running produces the same rows. */
function uuid(...parts) {
  const h = createHash("sha1").update(`byat:${parts.join(":")}`).digest("hex");
  const v = (c) => h.slice(...c);
  return `${v([0, 8])}-${v([8, 12])}-5${v([13, 16])}-a${v([17, 20])}-${v([20, 32])}`;
}

const q = (s) => (s == null || s === "" ? "null" : `'${String(s).replace(/'/g, "''")}'`);

// Which framework-level section each node sits in, and the order they appear.
// Mirrors the tiers in the diagram.
const LAYOUT = [
  ["Leadership", "Who owns the loop, and the brief everything inherits from.", ["cmo", "strategy"]],
  ["Customers", "Equation 1 — Lifetime Value − Acquisition Cost = Post-Acquisition Value.", ["customers", "acquisition", "retention"]],
  ["Campaigns", "Equation 2 — Sessions × Conversion Rate × Average Order Value = Revenue.", ["campaigns", "seo", "paid", "influencer", "owned"]],
  ["Measurement", "Reads the whole system back and scores both equations.", ["analytics"]],
  ["Your own nodes", "What's missing from this loop? Name it, staff it, defend it.", ["open"]],
];

// `fields.field_type` is constrained to text/textarea/richtext/number/radio/checkbox.
// Richer answer shapes render as a textarea for now, with the structure explained
// in helper text; widening the constraint is a UI decision, not a seed decision.
const FIELD_TYPE = { short: "text", text: "textarea", list: "textarea", pairs: "textarea", table: "textarea" };

const STRUCTURE_HINT = {
  list: (a) => `One per line — aim for ${a.count ?? 3}.`,
  pairs: (a) => `One pair per line as "${(a.labels ?? ["A", "B"]).join(" | ")}".`,
  table: (a) => `One row per line, columns separated by "|": ${(a.columns ?? []).join(" | ")}.`,
};

const FRAMEWORK_ID = uuid("framework");
const out = [];
const p = (s = "") => out.push(s);

p("-- ============================================================");
p("-- Migration 015 — Seed the Agentic Marketing Team framework");
p("--");
p("-- GENERATED by scripts/seed-sql.mjs in:");
p("--   github.com/OnDigitalMarketing/build-your-agentic-team");
p("-- Edit the markdown there and regenerate; don't hand-edit this file.");
p("--");
p("-- Every insert is ON CONFLICT DO NOTHING, so re-running is safe and will");
p("-- not overwrite questions edited in /admin/framework.");
p("-- ============================================================");
p();

p("-- ── Node metadata on steps (nullable — the Blueprint is unaffected) ──");
p("alter table public.steps add column if not exists node_kind   text;");
p("alter table public.steps add column if not exists node_mode   text;");
p("alter table public.steps add column if not exists node_file   text;");
p("alter table public.steps add column if not exists node_metric text;");
p();
p("-- Which \"## \" heading of the node's markdown file this question fills in.");
p("-- The file generator groups answers by it.");
p("alter table public.fields add column if not exists md_section text;");
p();

const loop = nodes.loop;
p("-- ── Framework ──");
p("insert into public.frameworks (id, title, description, version, is_active) values");
p(`  ('${FRAMEWORK_ID}', ${q("Agentic Marketing Team")}, ${q(loop?.body)}, '1.0', true)`);
p("on conflict (id) do nothing;");
p();

p("-- ── Sections ──");
p("insert into public.sections (id, framework_id, order_index, title, description) values");
p(
  LAYOUT.map(([title, desc], i) => `  ('${uuid("section", title)}', '${FRAMEWORK_ID}', ${i + 1}, ${q(title)}, ${q(desc)})`).join(",\n")
);
p("on conflict (id) do nothing;");
p();

const steps = [];
const fields = [];
let stepOrder = 0;

for (const [sectionTitle, , nodeIds] of LAYOUT) {
  const sectionId = uuid("section", sectionTitle);

  for (const id of nodeIds) {
    const node = nodes[id];
    if (!node) {
      console.error(`skipping unknown node "${id}"`);
      continue;
    }

    const stepId = uuid("step", id);
    stepOrder += 1;

    steps.push(
      `  ('${stepId}', '${FRAMEWORK_ID}', '${sectionId}', ${stepOrder}, ${q(id)}, ${q(node.title)}, ` +
        `${q(node.body)}, ${q(node.kind)}, ${q(node.mode)}, ${q(node.file)}, ${q(node.metric)})`
    );

    const interview = interviews[id];
    let fieldOrder = 0;

    if (interview) {
      // An authored interview: real questions, grouped by the file's headings.
      for (const section of interview.sections) {
        for (const ask of section.ask) {
          fieldOrder += 1;
          const hint = STRUCTURE_HINT[ask.type]?.(ask);
          const helper = [ask.help, hint].filter(Boolean).join(" ");
          fields.push(
            `  ('${uuid("field", id, ask.id)}', '${stepId}', ${fieldOrder}, ${q(ask.q)}, ${q(ask.id)}, ` +
              `${q(FIELD_TYPE[ask.type] ?? "textarea")}, ${q(ask.example)}, ${q(helper)}, ${q(section.section)})`
          );
        }
      }
    } else {
      // No interview written yet — fall back to one question per heading, so
      // every node is usable on day one and the wording gets refined in the CMS.
      for (const heading of node.sections) {
        fieldOrder += 1;
        fields.push(
          `  ('${uuid("field", id, heading)}', '${stepId}', ${fieldOrder}, ${q(heading)}, ` +
            `${q(heading.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, ""))}, ` +
            `'textarea', null, ${q(`Fills in the "${heading}" section of ${node.file}.`)}, ${q(heading)})`
        );
      }
    }
  }
}

p("-- ── Steps (one per node) ──");
p("insert into public.steps (id, framework_id, section_id, order_index, step_key, title, description, node_kind, node_mode, node_file, node_metric) values");
p(steps.join(",\n"));
p("on conflict (id) do nothing;");
p();

p("-- ── Fields (the questions) ──");
p("insert into public.fields (id, step_id, order_index, label, field_key, field_type, placeholder, helper_text, md_section) values");
p(fields.join(",\n"));
p("on conflict (id) do nothing;");
p();

console.error(`${steps.length} steps, ${fields.length} fields`);
console.log(out.join("\n"));
